[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

lib_deps =
  nrf24/RF24
  bodmer/TFT_eSPI
  lvgl/lvgl @ ^8.3.11

build_unflags = -std=gnu++11
build_flags =
  -I include
  -D USER_SETUP_LOADED
  -D USER_SETUP_ID=0
  -D RF24_SPI_SPEED=10000000
  -D LV_CONF_INCLUDE_SIMPLE
  -include include/User_Setup.h
  -std=gnu++17
  
